kylechui/nvim-surround

lua/nvim-surround/html.lua

* Switches to `vim.fn.input` over `vim.ui.input` for blocking input.

fix: Async input when HTML tag properties.

---

lua/nvim-surround/html.lua

I get an error when surround a html tag.
```
E5108: Error executing lua .../packer/start/nvim-surround/lua/nvim-surround/buffer.lua:154: attempt to concatenate a nil value
```
After some tests, it was found that the format of the return value of `get_tag` was wrong.
So, I simply fixed it.

fix: HTML tags not work.

---

lua/nvim-surround/html.lua
tests/surround_spec.lua

Hey! First of all, thanks for this great plugin :tada: I appreciate that I can hack away at surrounding objects using Lua and not Vimscript :sweat_smile:
As a contributor, I appreciate that this plugin has tests which I could easily extend to add a failing test case for the bug I found. The Lua code seems to also be well-structured and I could easily find the place I had to change to fix the bug.
---
I noticed a bug when surrounding with `t<div class="test">` - the final angle bracket was inserted twice. The final output was:
```txt
<div class="test">>some text</div>
```
instead of 
```diff
-<div class="test">>some text</div>
+<div class="test">some text</div>
```
I decided to add tests for surrounding with HTML tags (one of which was failing because of this bug), and then fix it in …

fix: Add final HTML tag angle bracket only once

---

tests/surround_spec.lua

When running the tests using `<Plug>PlenaryTestFile` the `shiftwidth` option was inherited from the user's config. For users that modified `shiftwidth` in their configuration the tests were failing. One of the tests ("nvim-surround can visual-line surround") indented a line while doing a surround but due to a different `shiftwidth`, the size of the indent did not match the expected 4 spaces.
This change makes all tests pass:
It is possible that other indent-related options should also be set so the tests behave consistently. `expandtab` comes to my mind.

tests: Use a consistent `shiftwidth` in tests

---

.github/workflows/integration.yml
.luacheckrc
lua/nvim-surround/config.lua

You can see an example CI run here: https://github.com/smjonas/nvim-surround/pull/1
Currently the tests are failing (locally as well), but that should be fixed separately.

ci: enable GitHub actions for stylua, luacheck and tests

---

lua/nvim-surround/config.lua
lua/nvim-surround/utils.lua

This improves performance by not reloading the entire plugin for each buffer, instead only using buffer-local maps to override the defaults when `buffer_setup` is called.

feat: Lazy load options.

---

lua/nvim-surround/init.lua

Firstly, this fixes the insert mode surround feature causing a `…/nvim-surround/lua/nvim-surround/init.lua:49: attempt to index local 'delimiters' (a nil value)` Lua error when pressing a key that doesn't map to any delimiter.
Secondly, this makes the indentation of the inner line in multi-line mode (`<c-g>S` by default) consistent with native auto-indent. Before this patch, if `shiftwidth` was `0` the inner line would have the same indent as the lines next to it.
This plugin would also falsely assume all tabs have a width equal to `shiftwidth`. Tab width is always defined by `tabstop` (unless `vartabstop` is set) and `shiftwidth` doesn't even have to be a multiple of `tabstop`, regardless of whether `expandtab` is set. Any configuration with `noexpandtab` and a `shiftwidth` that isn't …

fix: Error on invalid key, bad indent in insert_surround()

---

lua/nvim-surround/buffer.lua
lua/nvim-surround/config.lua
lua/nvim-surround/init.lua
lua/nvim-surround/textobjects.lua
lua/nvim-surround/utils.lua
tests/surround_spec.lua

Surround actions that involve opening delimiters like `cs<>` have slightly different behavior; it
will remove a space character if only one side has it, e.g. `cs<>` on
```
< hello world>
```
will yield
```
<hello world>
```

refactor!: Abstract text-objects code into separate file.

---

.github/ISSUE_TEMPLATE/bug_report.yml

Use textarea instead of input for the bug issue template, otherwise the input will be single-line and pressing enter will submit the issue.
The "To reproduce" section is also marked as required.

docs: Use textarea instead of input for issue template.

---

.github/workflows/integration.yml

This resolves the failing GitHub action.

ci: Change stylua action version to v1.

---

lua/nvim-surround/utils.lua

`getchar` returns a string for special keys ([ref](https://neovim.io/doc/user/builtin.html#getchar())). so `ys` + e.g. arrow keys will give some error messages.

fix: Handle special characters for `getchar`.

---

lua/nvim-surround/buffer.lua

Neovim on ARM is shipped with Lua5.1 instead of LuaJIT so this patch fix invalid binary number notation.
(related https://github.com/neovim/neovim/issues/19837)

Compatibility issue with Lua5.1

---

lua/nvim-surround/config.lua

Fix the `<Plug>(Nvim-surround-insert)` mapping since the mainline version mapped it in normal mode.
Tested on my local setup and verify it worked.

fix: <Plug>(nvim-surround-insert) mapping

---

lua/nvim-surround/init.lua

Fix #184 indentation when surrounding with line mode in normal mode.
Here, the second `"` should not be at col 0.

Add indentation when using line mode

---

lua/nvim-surround/treesitter.lua

I'm working primarily with the LaTeX parser, which for various reasons has multiple node types as possible targets for doing something like implementing `c`hange `s`urrounding `e`nvironment in Lua. Concretely, the text
```latex
\begin{SOMETHING}
% yadda yadda
\end{SOMETHING}
```
will be captured as either `generic_environment` or `math_environment` depending on the contents of `SOMETHING`. Anyway for this reason it would be nice to be able to use the `node` option to `get_selection` with multiple arguments; hence the change.

make get_selection optionally accept list

---

lua/nvim-surround/utils.lua

I add aliases `["f"] = "f"` and then nvim-surround will throw `bad argument #1 to 'ipairs' (table expected, got string)`  if we use change and delete operations

fix(utils): ensure chars is a table in ipairs

---

lua/nvim-surround/init.lua

In normal callback, the call to `normal_surround` would always send false for `line_mode`.

Fix (line mode): Use line mode parameter when possible

---

lua/nvim-surround/config.lua
lua/nvim-surround/input.lua

BREAKING CHANGE: User defined `invalid_key_behavior` handlers will be activated for special keys that don't have defined `surrounds`.

feat: Support special keys for `surrounds` definition (#179)

---

lua/nvim-surround/config.lua
lua/nvim-surround/input.lua

- config.get_char can now return strings that represent control characters, both single-byte (e.g. Ctrl+something) and multi-byte (e.g. Alt+something)
- New helper function `config.termcode` for generating keys for `surrounds` that use control characters.
BREAKING CHANGE: User defined `invalid_key_behavior` handlers will be activated for control characters that don't have defined `surrounds`.

feat: Support control characters for modifying `surrounds`. (#179)

---

lua/nvim-surround/config.lua

Fixes #197. The problem lies in the fact that `change_surround` and `delete_surround` both use `g@l` as a return value to enable dot-repeating. Changing the keymaps to `nnoremap` ignores user-defined mappings for `l`, and instead uses the (static) default value.

fix: Remove `remap = true` from keymaps.

---

lua/nvim-surround/queries.lua

fix: https://github.com/neovim/neovim/pull/22761

fix: Use vim.treesitter.query.parse() to avoid deprecation warning

---

lua/nvim-surround/config.lua
lua/nvim-surround/init.lua
tests/basics_spec.lua

Currently, there are some issues with linewise surround insertion and changing surrounds where the opening delimiter has only whitespace between it and the end of the line or where the closing delimiter has only whitespace between it and the beginning of the line.
```
foo
```
For instance, assuming default configuration, if `ySS{` is run on the above example text, the result is the following, with `·` marking space characters:
```
{·
····foo
}
```
If `cs{[` is then run, the result is:
```
[·
····foo
·]
```
If `cs]{` is then run, the result is:
```
{··
····foo
··}
```
`cs{}` will remove the trailing spaces after `{` and the leading spaces before `}` one by one, including the leading indentation before `}` if the entire text were space-indented beforehand. Correctly choosing between the …

Fix handling of whitespace when delimiters are on separate lines

---

lua/nvim-surround/cache.lua
lua/nvim-surround/config.lua
lua/nvim-surround/init.lua
tests/basics_spec.lua

This PR addresses #244.
As of this commit, given the input, where `|` denotes the cursor position:
```
let x = foo(args|);
```
`cS)(` yields:
```
let x = foo(|
args
);
```
The indentation of `args` depends on the indentation rules for the filetype.
We still need to iron out behavior for complex surrounds like HTML tags and functions. Currently, given the input, where `|` denotes the cursor position:
```
let x = foo(args|);
```
Both `csf` AND `cSf` with `bar` would yield:
```
let x = |bar(args);
```
This follows because the change target selection is just the `foo`. However, users may instead want the result to be:
```
let x = |bar(
args
);
```
This is more useful because otherwise, `cs` and `cS` would be exhibiting the same behavior.

Implement change_line mapping

---

lua/nvim-surround/config.lua
tests/configuration_spec.lua
tests/dot_repeat_spec.lua

Also corrects a dot-repeat test
Sorry, it seems https://github.com/kylechui/nvim-surround/pull/261 got closed after an emotional rollercoaster. In any case the tests are working now. Thanks for taking a look!

fix: line surrounds are properly dot-repeatable

---

lua/nvim-surround/input.lua

In ‘config.translate_opts()’, the chars specified in the ‘surrounds’
portion of a configuration are translated to Vim internal representation
in order to support special characters.  As a result though, we need to
actually translate the users input.  Otherwise configuration of certain
Unicode characters such as U+2019 RIGHT SINGLE QUOTATION MARK may not
work.

fix: Translate char to termcodes when reading input (#271)

---

lua/nvim-surround/config.lua

This caused me a bug where the keymap for `change` would be disabled when configuring `change_line = false`
The bug occurs because of the logic in `set_keymap`
```lua
-- If the keymap is disabled
if not args.lhs then
-- If the mapping is disabled globally, do nothing
if not M.user_opts.keymaps[args.name] then
return
end
-- Otherwise disable the global keymap
args.lhs = M.user_opts.keymaps[args.name]
args.rhs = "<NOP>"
end
vim.keymap.set(args.mode, args.lhs, args.rhs, args.opts)
```
Entering this function for `change_line` we get `lhs = false` (correct) but since `name = "change"` (incorrect) it thinks that the mapping is not globally disabled so it overrides the lhs for `change` with `"<NOP>"`
The problem is resolved by correctly giving the `change_line` keymap its own name (like …

fix: correctly name keymap for change_line

---

doc/nvim-surround.txt

Re: discussion https://github.com/kylechui/nvim-surround/discussions/259
Added a reference to the relevant help text for motions, specifically for people who aren't super familiar with vim and never heard of text objects.
I think that the `:h motion` part is pretty facepalm-worthy obvious, but for someone who doesn't know about text-objects, I think it'd be hard to find info on `a` and `i`. But it would feel weird to give the suggestion for `:h text-objects` without mentioning `:h motion`.

docs: added a reference to relevant helptexts for motions

---

lua/nvim-surround/buffer.lua

I've got remapped `a` / `g` and this `normal` caused some problems (nothing was working)

fix: add bang to the normal command

---

lua/nvim-surround/init.lua

It seems that this judgment will always be followed by the result

Remove logic that may not be useful

---

lua/nvim-surround/config.lua

Do not set dot repeat to indentation as it is misleading and messes with undo.
As of now, the default indentation function will perform its action and thus will set the dot-repeat to indent the lines. So when the user types `.` hoping to repeat some surrounds, "nothing" will happen, but it will stack on the undotree. I'm not sure about a workaround for this. I've thought of performing the action in an embedded headless nvim instance and taking back the result and changing the region to the updated text, but it seems overkill.

fix(dot-repeat): clear dot-repeat after indentation

---

lua/nvim-surround/annotations.lua

Type linter complains that missing options should be valid in configuration, when in fact they're optional. This marks the fields as optional.

fix: Mark fields in user_option and user_surround as optional

---

lua/nvim-surround/functional.lua

This is also arguably more correct, since the previous version would also wrap non-list tables like `{ 1 = 'a', 3 = 'b' }`.
Fixes #321

fix: replace deprecated `vim.tbl_islist` by native Lua function

---

lua/nvim-surround/input.lua
tests/configuration_spec.lua

`getcharstr()` already returns raw internal termcodes, it is wrong to call nvim_replace_termcodes on its result.
This effectively reverts PR #273
refs: neovim/neovim#29034
fixes #325
---
The original PR #273 was supposedly fixing the issue #271, @Mango0x45 could you check if you now get that problem back or if #318 was the actual correct fix ?

Don't translate termcodes twice on input

---

lua/nvim-surround/config.lua
tests/configuration_spec.lua

If the user has redefined `find = "‘.-’"`, then it makes more sense for default `delete` to honor that and trim quotes, rather than fail and do nothing.

fix: Default delete should work if `find` key is sane.

---

doc/nvim-surround.txt
lua/nvim-surround/annotations.lua
lua/nvim-surround/buffer.lua
lua/nvim-surround/init.lua
tests/configuration_spec.lua

This aims to add a "sticky" option for `move_cursor`, where "sticky" keeps the cursor "stuck" to whatever character the cursor was on before the surround action. See the unit tests in this PR for an idea of how exactly this would work.
One nice use case for this is dot-repeating with a sticky cursor, as one can do `ysiw].` to surround a word with double brackets, whereas the old behavior would do something like `hello` &rarr; `[[]hello]` (since the dot-repeat would surround the open square bracket).
Please react to show interest in this feature!
Replaces #289; is a partial solution to #281

feat: Improve `move_cursor`.

---

lua/nvim-surround/annotations.lua
lua/nvim-surround/config.lua
tests/configuration_spec.lua

Inspired by the question in #341. Makes the UX more uniform between the "simple" version of the `add` key and more advanced callback functions.

feat(config): Automatically wrap `add` key in a table.

---

lua/nvim-surround/config.lua
lua/nvim-surround/init.lua

to prevent from loading them on startup.

Defer loading some modules

---

lua/nvim-surround/cache.lua
lua/nvim-surround/init.lua
lua/nvim-surround/utils.lua
tests/basics_spec.lua

TODO: Repeat deletions, unit test stuff.
Feels like there's a cleaner way to parse the user input than the scuffed `nil` stuff I have right now. Although at the very least it's isolated in the `get_char` function :thinking:

feat: Repeat operations for add/change/delete.

---

.github/workflows/luarocks-release.yml
.github/workflows/release-please.yml

Using a GitHub private access token in order to allow other actions to run on top of the `release-please` action, since otherwise they are blocked to avoid recursive actions.
> You will want to configure a GitHub Actions secret with a Personal Access Token
> if you want GitHub Actions CI checks to run on Release Please PRs.
Ref: https://github.com/googleapis/release-please-action?tab=readme-ov-file#other-actions-on-release-please-prs

fix: Attempt to unblock `luarocks-release`.

---

lua/nvim-surround/queries.lua

The `vim.treesitter.language.get_lang` function was added in Neovim v0.11[1], so we should not assume it to exist. The implementation is pretty short/simple so we just copy it into our codebase.
[1]: https://neovim.io/doc/user/news-0.11.html

fix: Compatibility issue with Neovim <v0.11.
